### PR TITLE
removed "Results generated by style50"

### PR DESCRIPTION
**Pull request by dmalan**
@crossroads1112 why this addition?

### CODE REVIEW

**Comment by cmlsharp** [comment]
check50 has a similar message. Reason being that if there are issues it's easy to tell what version the student has installed just from their screenshot of the issue. It made fielding emails slightly easier. I don't mind removing if it's an issue

**Comment by kzidane** [comment]
I agree with @crossroads1112. Saves us some extra digging sometimes.

**Review by cmlsharp — COMMENTED** [review]
I'm adding this so pull request reminders will stop pinging me. See the comment above.

**Comment by cmlsharp** [comment]
I'm going to revert the removal of "results generated by" at least temporarily so we can push this bug fix out.

**Review by cmlsharp — APPROVED** [review]

**Pull request merged**
